#!/bin/bash -e
# Wrapper for launching flannel via docker.
#
# Make sure to set FLANNEL_IMAGE_TAG to an image tag published here:
# https://quay.io/repository/coreos/flannel?tab=tags Alternatively,
# override FLANNEL_IMAGE to a custom image.

function require_ev_all() {
	for rev in $@ ; do
		if [[ -z "${!rev}" ]]; then
			echo "${rev}" is not set
			exit 1
		fi
	done
}

function require_ev_one() {
	for rev in $@ ; do
		if [[ ! -z "${!rev}" ]]; then
			return
		fi
	done
	echo One of $@ must be set
	exit 1
}

if [[ -n "${FLANNEL_VER}" ]]; then
	echo FLANNEL_VER environment variable is deprecated, please use FLANNEL_IMAGE_TAG instead
fi

if [[ -n "${FLANNEL_IMG}" ]]; then
	echo FLANNEL_IMG environment variable is deprecated, please use FLANNEL_IMAGE_URL instead
fi

FLANNEL_IMAGE_TAG="${FLANNEL_IMAGE_TAG:-${FLANNEL_VER}}"

require_ev_one FLANNEL_IMAGE FLANNEL_IMAGE_TAG

FLANNEL_IMAGE_URL="${FLANNEL_IMAGE_URL:-${FLANNEL_IMG:-quay.io/coreos/flannel}}"
FLANNEL_IMAGE="${FLANNEL_IMAGE:-${FLANNEL_IMAGE_URL}:${FLANNEL_IMAGE_TAG}}"

ETCD_SSL_DIR="${ETCD_SSL_DIR:-/etc/ssl/etcd}"
if [[ -d "${ETCD_SSL_DIR}" ]]; then
	DOCKER_RUN_ARGS="${DOCKER_RUN_ARGS} \
		--mount type=bind,bind-propagation=rprivate,source=${ETCD_SSL_DIR},target=${ETCD_SSL_DIR},readonly \
	"
fi

if [[ -S "${NOTIFY_SOCKET}" ]]; then
	DOCKER_RUN_ARGS="${DOCKER_RUN_ARGS} \
		--env NOTIFY_SOCKET=/run/systemd/notify \
		--mount type=bind,bind-propagation=rprivate,source=${NOTIFY_SOCKET},target=/run/systemd/notify \
	"
fi

mkdir --parents /run/flannel

DOCKER="${DOCKER:-/usr/bin/docker}"
set -x
exec ${DOCKER} ${DOCKER_GLOBAL_ARGS} \
	run ${DOCKER_RUN_ARGS} \
	--entrypoint=/opt/bin/flanneld \
	--net=host \
	--mount type=bind,bind-propagation=rprivate,source=/run/flannel,target=/run/flannel \
	--mount type=bind,bind-propagation=rprivate,source=/etc/ssl/certs,target=/etc/ssl/certs,readonly \
	--mount type=bind,bind-propagation=rprivate,source=/usr/share/ca-certificates,target=/usr/share/ca-certificates,readonly \
	--mount type=bind,bind-propagation=rprivate,source=/etc/hosts,target=/etc/hosts,readonly \
	--mount type=bind,bind-propagation=rprivate,source=/etc/resolv.conf,target=/etc/resolv.conf,readonly \
	${FLANNEL_IMAGE} \
		${FLANNEL_IMAGE_ARGS} \
		"$@"
