#!/bin/bash -e

ENV=$1

if [ -z "$ENV" ]; then
        echo usage: $0 /etc/environment
        exit 1
fi
# test for rw
touch $ENV
if [ $? -ne 0 ]; then
        echo exiting, unable to modify: $ENV
        exit 1
fi

sed -i -e '/^FLATCAR_PUBLIC_IPV4=/d' \
    -e '/^FLATCAR_PRIVATE_IPV4=/d' \
    "${ENV}"

# We spin loop until the nova-agent sets up the ip addresses
function get_ip () {
	PREFIX="$1"
	while [ 1 ]; do
		IP=""
		IF="$(ip -4 route get $PREFIX | awk '{for(i=1;i<=NF;i++)if($i=="dev")print $(i+1)}')"
		if [ "$IF" != "" ] && [ "$IF" != "lo" ]; then
		  IP=$(ifconfig $IF | awk '/inet /{print $2}')
		fi
		if [ "$IP" != "" ]; then
			break
		fi
		sleep .1
	done
	echo "$IP"
}

function get_private_ip () {
	STARTSWITH="$1"
	IP=""
	while [ 1 ]; do
		IP="$(ifconfig | awk "/inet $STARTSWITH/"'{print $2}' | head -n 1)"
		if [ "$IP" != "" ]; then
			break
		fi
		sleep .1
	done
	echo "$IP"
}

# Gets IP for interface with route to 1.0.0.0
echo FLATCAR_PUBLIC_IPV4=$(get_ip 1) >> $ENV
# Gets IP starting with 10.
echo FLATCAR_PRIVATE_IPV4=$(get_private_ip "10.") >> $ENV
